---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-v2
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: magalixcorp/mywebserver:2
        name: nginx
