---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-v1
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: magalixcorp/mywebserver:1
        name: nginx
